### PR TITLE
fix: rearrange bitwise operations while transform

### LINKED ISSUE #120: Reduce bitwise operations in transform formulas
Wollac proposed changes to reduce the number of bitwise operations used in transform formulas within [entangled PR #803](https://github.com/iotaledger/entangled/pull/803). Let's synchronize.

### PR DESCRIPTION
**Pull request by wusyong**
While optimized transfomr function holds same results, operations in
each assignments are not the same number. So we reduce and rearrange
some operators back to original positions. Improved performance is still
valid.

Fix #120

### CODE REVIEW

File: src/pow_avx.c [hunk 1]
```diff
@@ -31,10 +31,9 @@ static void transform256(__m256i *lmid, __m256i *hmid)
 
             alpha = lfrom[t1];
             beta = hfrom[t1];
-            delta = _mm256_xor_si256(lfrom[t2], beta); /* lfrom[t2] ^ beta */
-
-            lto[j] = _mm256_andnot_si256(_mm256_and_si256(delta, alpha),
-                                         one); /* ~(delta & alpha) */
+            delta = _mm256_and_si256( alpha, _mm256_xor_si256(lfrom[t2], beta));
+                    /* alpha & (lfrom[t2] ^ beta) */
+            lto[j] = _mm256_andnot_si256(delta, one); /* ~(delta & alpha) */
```
Comment (marktwtn) [inline src/pow_avx.c]: The comment needs to be revised to `~delta`.

File: src/pow_avx.c [hunk 2]
```diff
@@ -49,10 +48,9 @@ static void transform256(__m256i *lmid, __m256i *hmid)
         t2 = indices[j + 1];
         alpha = lfrom[t1];
         beta = hfrom[t1];
-        delta = _mm256_xor_si256(lfrom[t2], beta); /* lfrom[t2] ^ beta */
-
-        lto[j] = _mm256_andnot_si256(_mm256_and_si256(delta, alpha),
-                                     one); /* ~(delta & alpha) */
+        delta = _mm256_and_si256( alpha, _mm256_xor_si256(lfrom[t2], beta));
+                /* alpha & (lfrom[t2] ^ beta) */
+        lto[j] = _mm256_andnot_si256(delta, one); /* ~(delta & alpha) */
```
Comment (marktwtn) [inline src/pow_avx.c]: Ditto.

File: src/pow_c.c [hunk 3]
```diff
@@ -43,9 +43,9 @@ static void transform64(uint64_t *lmid, uint64_t *hmid)
         int t2 = indices[j + 1];
         alpha = lfrom[t1];
         beta = hfrom[t1];
-        delta = beta ^ lfrom[t2];
-        lto[j] = ~(delta & alpha);
-        hto[j] = delta | (alpha ^ hfrom[t2]);
+        delta = alpha & (lfrom[t2] ^ beta);
+        lto[j] = ~delta;
+        hto[j] = (alpha ^ hfrom[t2]) | delta;
```
Comment (marktwtn) [inline src/pow_c.c:48]: What is changing the position of `delta` for?
For consistency?

Comment (wusyong) [reply src/pow_c.c:48]: Yes, for consistency.

**Comment by marktwtn** [comment]
> While optimized transfomr function holds same results, operations in
> each assignments are not the same number.

Typo: transfomr -> transform.
